# RNA polymerase classification for snRNA genes
# This configuration file defines which RNA types are transcribed by
# RNA Polymerase II vs RNA Polymerase III

rna_polymerases:
  pol2:
    description: "RNA Polymerase II transcribed snRNAs"
    types:
      - U1
      - U2
      - U3
      - U4
      - U4atac
      - U5
      - U7
      - U8
      - U11
      - U12
      - OrCD1
  
  pol3:
    description: "RNA Polymerase III transcribed snRNAs"
    types:
      - noeCR34335
      - Arthropod_7SK
      - 7SL
      - RNase_MRP
      - RNaseP_nuc
      - U6
      - U6atac
      - tRNAsec
      - snoRNAMe18SA1806

# Default e-value thresholds for each RNA type
evalues:
  Arthropod_7SK: 1e-15
  OrCD1: 1e-10
  RNase_MRP: 1e-10
  RNaseP_nuc: 1e-10
  U1: 1e-15
  U2: 1e-15
  U3: 1e-10
  U4: 1e-10
  U4atac: 1e-10
  U5: 1e-10
  U6: 1e-10
  U6atac: 1e-10
  U7: 1e-4
  U8: 1e-4
  U11: 1e-4
  U12: 1e-4
  tRNAsec: 1e-10
  snoRNAMe18SA1806: 1e-3

# Genes to exclude for specific taxonomic groups
exclude_genes:
  Insecta:
    - RNaseP_nuc

# Default upstream region length in nucleotides
upstream_length: 100

# Strict mode for upstream extraction (only exact length regions)
upstream_strict: true

# Similarity threshold for filtering nearly identical sequences (percentage)
similarity_threshold: 98

# Low complexity filtering thresholds (as fractions: 0.5 = 50%)
low_complexity:
  homopolymer: 0.5      # Max fraction for any single nucleotide
  dinucleotide: 0.75    # Max fraction for any dinucleotide pattern
  trinucleotide: 0.75   # Max fraction for any trinucleotide pattern

# BLAST query names mapping (filename -> gene name for GFF3)
blast_queries:
  noeCR34335: noeCR34335
  snoRNAMe18SA1806: snoRNAMe18SA1806
  7SL: 7SL

# Promoter annotation settings by taxonomic group
# Applied in order from most specific to least specific (species > genus > family > order > suborder > infraorder > class)
promoter_annotation:
  Muscomorpha:
    kmers:
      - AATTCTCA

  Muscidae:
    kmers:
      - AATTCDCAT
    promoter_start: 3
    promoter_length: 22

  Glossata:
    kmers:
      - ATCGCG

  Drosophilidae:
    kmers:
      - TTCYCAA
    promoter_length: 22
    promoter_start: 5

  Nematocera:
    kmers:
      - ATCRCTA

  Hymenoptera:
    kmers:
      - TTCTCRC

  Tachinidae:
    kmers:
      - AATTCYCRT
    promoter_length: 21
    promoter_start: 2

  # Default settings if no taxonomic match found
  default:
    promoter_length: 20
    promoter_start: 3
    search_start: -45
    search_end: -70
